// Generated by hub/tools/make_app_fixtures.py from real hub responses. Do not edit.

enum HubFixtures {
    static let pair = #"""
{
  "device_id": "90960154",
  "device_name": "Fixture Mac",
  "token": "REDACTED-FIXTURE-TOKEN"
}
"""#

    static let status = #"""
{
  "gpu": {
    "busy": false,
    "busy_for_s": 0,
    "naota_healthy": true,
    "served": 0,
    "waiting": 0
  },
  "jobs": {
    "hub": {
      "blocked": 1,
      "done": 3
    },
    "mac": {
      "done": 2
    }
  },
  "mac_worker": {
    "last_seen": 1790909252.060589,
    "name": "mac-worker"
  },
  "sessions": {
    "blocked": 1,
    "recent": [
      {
        "created_at": 1790909252.164167,
        "detail": "Add to campaign.yaml, then retry: stranger (999)",
        "number": 61,
        "state": "blocked"
      },
      {
        "created_at": 1790909252.007405,
        "detail": "1 proposal(s) to review",
        "number": 60,
        "state": "review"
      }
    ]
  },
  "time": 1790909252.3868759,
  "vault": {
    "configured": true,
    "push_branches": false
  }
}
"""#

    static let sessions = #"""
{
  "sessions": [
    {
      "created_at": 1790909252.164167,
      "detail": "Add to campaign.yaml, then retry: stranger (999)",
      "number": 61,
      "state": "blocked"
    },
    {
      "created_at": 1790909252.007405,
      "detail": "1 proposal(s) to review",
      "number": 60,
      "state": "review"
    }
  ]
}
"""#

    static let sessionReady = #"""
{
  "created_at": 1790909252.007405,
  "detail": null,
  "jobs": [
    {
      "attempts": 1,
      "error": null,
      "id": 1,
      "lane": "hub",
      "progress": null,
      "stage": "s1",
      "state": "done",
      "track": null,
      "updated_at": 1790909252.051019
    },
    {
      "attempts": 1,
      "error": null,
      "id": 2,
      "lane": "mac",
      "progress": {
        "at": 1790909252.055309,
        "done": 1,
        "total": 1
      },
      "stage": "s2",
      "state": "done",
      "track": 1,
      "updated_at": 1790909252.056583
    },
    {
      "attempts": 1,
      "error": null,
      "id": 3,
      "lane": "mac",
      "progress": {
        "at": 1790909252.0585349,
        "done": 1,
        "total": 1
      },
      "stage": "s2",
      "state": "done",
      "track": 2,
      "updated_at": 1790909252.059632
    },
    {
      "attempts": 1,
      "error": null,
      "id": 4,
      "lane": "hub",
      "progress": null,
      "stage": "s3",
      "state": "done",
      "track": null,
      "updated_at": 1790909252.162404
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790909252.050731,
    "session": 60,
    "stage3": {
      "at": 1790909252.162028,
      "branch": "scribe/session-060",
      "commit": "97a8744b4a9742e9a2bdf078115a229a011b8cb5",
      "pushed": false,
      "utterances": 2
    },
    "tracks": [
      {
        "discord_id": "1001",
        "duration_s": 1.0,
        "file": "1-gm_user.wav",
        "index": 1,
        "speaker": {
          "label": "Gamemaster/DM",
          "pc": null,
          "role": "dm"
        },
        "username": "gm_user"
      },
      {
        "discord_id": "1002",
        "duration_s": 1.0,
        "file": "2-pat_user.wav",
        "index": 2,
        "speaker": {
          "label": "Pat/Alpha",
          "pc": "alpha",
          "role": "player"
        },
        "username": "pat_user"
      }
    ],
    "unmapped": []
  },
  "number": 60,
  "state": "ready"
}
"""#

    static let proposals = #"""
{
  "batch": {
    "created_at": 1790909252.260316,
    "id": 1,
    "provider": "custom",
    "publish_commit": null,
    "published_at": null,
    "session": 60,
    "summary": null,
    "vault": "dm",
    "violations": []
  },
  "proposals": [
    {
      "after": "Tall, with a **new** scar.",
      "batch": 1,
      "before": "Tall.",
      "check_error": null,
      "conflicts": [],
      "edited_after": null,
      "entity": "Pat Alpha",
      "evidence": [
        {
          "end_ms": 2800,
          "speaker": "Pat/Alpha",
          "start_ms": 2000,
          "text": "Line from track 2.",
          "track": 2,
          "utterance_id": "t2-2000"
        }
      ],
      "from_path": null,
      "id": 1,
      "key": null,
      "op": "update-section",
      "proposal_id": "p-060-001",
      "rationale": "Pat was wounded at the gate.",
      "secret": false,
      "section": "Appearance",
      "state": "pending",
      "target": "Characters/PCs/Pat-Alpha.md",
      "updated_at": 1790909252.260316
    },
    {
      "after": "x",
      "batch": 1,
      "before": null,
      "check_error": "no section titled 'Quotes'",
      "conflicts": [],
      "edited_after": null,
      "entity": "Pat Alpha",
      "evidence": [
        {
          "end_ms": 2800,
          "speaker": "Pat/Alpha",
          "start_ms": 2000,
          "text": "Line from track 2.",
          "track": 2,
          "utterance_id": "t2-2000"
        }
      ],
      "from_path": null,
      "id": 2,
      "key": null,
      "op": "update-section",
      "proposal_id": "p-060-002",
      "rationale": "A section that doesn't exist.",
      "secret": false,
      "section": "Quotes",
      "state": "rejected_by_checks",
      "target": "Characters/PCs/Pat-Alpha.md",
      "updated_at": 1790909252.260316
    }
  ]
}
"""#

    static let decided = #"""
{
  "after": "Tall, with a **new** scar.",
  "batch": 1,
  "before": "Tall.",
  "check_error": null,
  "conflicts": [],
  "edited_after": null,
  "entity": "Pat Alpha",
  "evidence": [
    {
      "end_ms": 2800,
      "speaker": "Pat/Alpha",
      "start_ms": 2000,
      "text": "Line from track 2.",
      "track": 2,
      "utterance_id": "t2-2000"
    }
  ],
  "from_path": null,
  "id": 1,
  "key": null,
  "op": "update-section",
  "proposal_id": "p-060-001",
  "rationale": "Pat was wounded at the gate.",
  "secret": false,
  "section": "Appearance",
  "state": "accepted",
  "target": "Characters/PCs/Pat-Alpha.md",
  "updated_at": 1790909252.263508
}
"""#

    static let publishDryRun = #"""
{
  "applied": 1,
  "commit": null,
  "dry_run": true,
  "files": [
    "Characters/PCs/Pat-Alpha.md",
    "_INBOX/Session-060-Downstream-Plan.md",
    "_INBOX/Session-060-Full-Transcript.md",
    "_INBOX/Session-060-proposals.json"
  ],
  "pushed": false
}
"""#

    static let sessionBlocked = #"""
{
  "created_at": 1790909252.164167,
  "detail": "Add to campaign.yaml, then retry: stranger (999)",
  "jobs": [
    {
      "attempts": 1,
      "error": "unmapped speaker(s): stranger (999)",
      "id": 5,
      "lane": "hub",
      "progress": null,
      "stage": "s1",
      "state": "blocked",
      "track": null,
      "updated_at": 1790909252.1860092
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790909252.185778,
    "session": 61,
    "stage3": null,
    "tracks": [
      {
        "discord_id": "999",
        "duration_s": 1.0,
        "file": "1-stranger.wav",
        "index": 1,
        "speaker": null,
        "username": "stranger"
      }
    ],
    "unmapped": [
      {
        "discord_id": "999",
        "index": 1,
        "username": "stranger"
      }
    ]
  },
  "number": 61,
  "state": "blocked"
}
"""#

    static let utterances = #"""
{
  "offset": 0,
  "total": 2,
  "utterances": [
    {
      "confidence": 0.9,
      "end_ms": 1800,
      "id": "t1-1000",
      "role": "dm",
      "speaker": "Gamemaster/DM",
      "start_ms": 1000,
      "text": "Line from track 1.",
      "track": 1
    },
    {
      "confidence": 0.9,
      "end_ms": 2800,
      "id": "t2-2000",
      "role": "player",
      "speaker": "Pat/Alpha",
      "start_ms": 2000,
      "text": "Line from track 2.",
      "track": 2
    }
  ]
}
"""#

    static let campaign = #"""
{
  "speakers": [
    {
      "discord_id": "1001",
      "label": "Gamemaster/DM",
      "role": "dm",
      "usernames": [
        "gm_user"
      ]
    },
    {
      "discord_id": "1002",
      "label": "Pat/Alpha",
      "pc": "alpha",
      "role": "player",
      "usernames": [
        "pat_user"
      ]
    }
  ],
  "vocabulary_prompt": "A game in a test world. Alpha talks with Beta."
}
"""#

    static let devices = #"""
{
  "devices": [
    {
      "created_at": 1790909252.0035682,
      "id": "90960154",
      "last_seen": 1790909252.392054,
      "name": "Fixture Mac",
      "revoked_at": null,
      "scope": "app"
    },
    {
      "created_at": 1790909252.004319,
      "id": "88945a7b",
      "last_seen": 1790909252.060458,
      "name": "mac-worker",
      "revoked_at": null,
      "scope": "worker"
    }
  ]
}
"""#

    static let upload = #"""
{
  "job": 1,
  "session": 60
}
"""#

}
