// Generated by hub/tools/make_app_fixtures.py from real hub responses. Do not edit.

enum HubFixtures {
    static let pair = #"""
{
  "device_id": "600ea29d",
  "device_name": "Fixture Mac",
  "token": "REDACTED-FIXTURE-TOKEN"
}
"""#

    static let status = #"""
{
  "gpu": {
    "busy": false,
    "busy_for_s": 0,
    "naota_healthy": true,
    "served": 0,
    "waiting": 0
  },
  "jobs": {
    "hub": {
      "blocked": 1,
      "done": 2
    },
    "mac": {
      "done": 2
    }
  },
  "mac_worker": {
    "last_seen": 1790874866.148905,
    "name": "mac-worker"
  },
  "sessions": {
    "blocked": 1,
    "recent": [
      {
        "created_at": 1790874866.4422379,
        "detail": "Add to campaign.yaml, then retry: stranger (999)",
        "number": 61,
        "state": "blocked"
      },
      {
        "created_at": 1790874865.9500449,
        "detail": null,
        "number": 60,
        "state": "ready"
      }
    ]
  },
  "time": 1790874866.489602,
  "vault": {
    "configured": true,
    "push_branches": false
  }
}
"""#

    static let sessions = #"""
{
  "sessions": [
    {
      "created_at": 1790874866.4422379,
      "detail": "Add to campaign.yaml, then retry: stranger (999)",
      "number": 61,
      "state": "blocked"
    },
    {
      "created_at": 1790874865.9500449,
      "detail": null,
      "number": 60,
      "state": "ready"
    }
  ]
}
"""#

    static let sessionReady = #"""
{
  "created_at": 1790874865.9500449,
  "detail": null,
  "jobs": [
    {
      "attempts": 1,
      "error": null,
      "id": 1,
      "lane": "hub",
      "stage": "s1",
      "state": "done",
      "track": null,
      "updated_at": 1790874866.1250508
    },
    {
      "attempts": 1,
      "error": null,
      "id": 2,
      "lane": "mac",
      "stage": "s2",
      "state": "done",
      "track": 1,
      "updated_at": 1790874866.138325
    },
    {
      "attempts": 1,
      "error": null,
      "id": 3,
      "lane": "mac",
      "stage": "s2",
      "state": "done",
      "track": 2,
      "updated_at": 1790874866.1453319
    },
    {
      "attempts": 1,
      "error": null,
      "id": 4,
      "lane": "hub",
      "stage": "s3",
      "state": "done",
      "track": null,
      "updated_at": 1790874866.437299
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790874866.124361,
    "session": 60,
    "stage3": {
      "at": 1790874866.436314,
      "branch": "scribe/session-060",
      "commit": "4b4a17a0d1aca457aa105319427281b76d77ea0c",
      "pushed": false,
      "utterances": 2
    },
    "tracks": [
      {
        "discord_id": "1001",
        "duration_s": 1.0,
        "file": "1-gm_user.wav",
        "index": 1,
        "speaker": {
          "label": "Gamemaster/DM",
          "pc": null,
          "role": "dm"
        },
        "username": "gm_user"
      },
      {
        "discord_id": "1002",
        "duration_s": 1.0,
        "file": "2-pat_user.wav",
        "index": 2,
        "speaker": {
          "label": "Pat/Alpha",
          "pc": "alpha",
          "role": "player"
        },
        "username": "pat_user"
      }
    ],
    "unmapped": []
  },
  "number": 60,
  "state": "ready"
}
"""#

    static let sessionBlocked = #"""
{
  "created_at": 1790874866.4422379,
  "detail": "Add to campaign.yaml, then retry: stranger (999)",
  "jobs": [
    {
      "attempts": 1,
      "error": "unmapped speaker(s): stranger (999)",
      "id": 5,
      "lane": "hub",
      "stage": "s1",
      "state": "blocked",
      "track": null,
      "updated_at": 1790874866.4856389
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790874866.484996,
    "session": 61,
    "stage3": null,
    "tracks": [
      {
        "discord_id": "999",
        "duration_s": 1.0,
        "file": "1-stranger.wav",
        "index": 1,
        "speaker": null,
        "username": "stranger"
      }
    ],
    "unmapped": [
      {
        "discord_id": "999",
        "index": 1,
        "username": "stranger"
      }
    ]
  },
  "number": 61,
  "state": "blocked"
}
"""#

    static let utterances = #"""
{
  "offset": 0,
  "total": 2,
  "utterances": [
    {
      "confidence": 0.9,
      "end_ms": 1800,
      "id": "t1-1000",
      "role": "dm",
      "speaker": "Gamemaster/DM",
      "start_ms": 1000,
      "text": "Line from track 1.",
      "track": 1
    },
    {
      "confidence": 0.9,
      "end_ms": 2800,
      "id": "t2-2000",
      "role": "player",
      "speaker": "Pat/Alpha",
      "start_ms": 2000,
      "text": "Line from track 2.",
      "track": 2
    }
  ]
}
"""#

    static let campaign = #"""
{
  "speakers": [
    {
      "discord_id": "1001",
      "label": "Gamemaster/DM",
      "role": "dm",
      "usernames": [
        "gm_user"
      ]
    },
    {
      "discord_id": "1002",
      "label": "Pat/Alpha",
      "pc": "alpha",
      "role": "player",
      "usernames": [
        "pat_user"
      ]
    }
  ],
  "vocabulary_prompt": "A game in a test world. Alpha talks with Beta."
}
"""#

    static let devices = #"""
{
  "devices": [
    {
      "created_at": 1790874865.937695,
      "id": "600ea29d",
      "last_seen": 1790874866.506568,
      "name": "Fixture Mac",
      "revoked_at": null,
      "scope": "app"
    },
    {
      "created_at": 1790874865.940313,
      "id": "753da96d",
      "last_seen": 1790874866.148426,
      "name": "mac-worker",
      "revoked_at": null,
      "scope": "worker"
    }
  ]
}
"""#

    static let upload = #"""
{
  "job": 1,
  "session": 60
}
"""#

}
