// Generated by hub/tools/make_app_fixtures.py from real hub responses. Do not edit.

enum HubFixtures {
    static let pair = #"""
{
  "device_id": "7c1f9db3",
  "device_name": "Fixture Mac",
  "token": "REDACTED-FIXTURE-TOKEN"
}
"""#

    static let status = #"""
{
  "gpu": {
    "busy": false,
    "busy_for_s": 0,
    "naota_healthy": true,
    "served": 0,
    "waiting": 0
  },
  "jobs": {
    "hub": {
      "blocked": 1,
      "done": 2
    },
    "mac": {
      "done": 2
    }
  },
  "mac_worker": {
    "last_seen": 1790906967.3756878,
    "name": "mac-worker"
  },
  "sessions": {
    "blocked": 1,
    "recent": [
      {
        "created_at": 1790906967.540237,
        "detail": "Add to campaign.yaml, then retry: stranger (999)",
        "number": 61,
        "state": "blocked"
      },
      {
        "created_at": 1790906967.3082938,
        "detail": null,
        "number": 60,
        "state": "ready"
      }
    ]
  },
  "time": 1790906967.568532,
  "vault": {
    "configured": true,
    "push_branches": false
  }
}
"""#

    static let sessions = #"""
{
  "sessions": [
    {
      "created_at": 1790906967.540237,
      "detail": "Add to campaign.yaml, then retry: stranger (999)",
      "number": 61,
      "state": "blocked"
    },
    {
      "created_at": 1790906967.3082938,
      "detail": null,
      "number": 60,
      "state": "ready"
    }
  ]
}
"""#

    static let sessionReady = #"""
{
  "created_at": 1790906967.3082938,
  "detail": null,
  "jobs": [
    {
      "attempts": 1,
      "error": null,
      "id": 1,
      "lane": "hub",
      "progress": null,
      "stage": "s1",
      "state": "done",
      "track": null,
      "updated_at": 1790906967.361907
    },
    {
      "attempts": 1,
      "error": null,
      "id": 2,
      "lane": "mac",
      "progress": {
        "at": 1790906967.368444,
        "done": 1,
        "total": 1
      },
      "stage": "s2",
      "state": "done",
      "track": 1,
      "updated_at": 1790906967.370047
    },
    {
      "attempts": 1,
      "error": null,
      "id": 3,
      "lane": "mac",
      "progress": {
        "at": 1790906967.373513,
        "done": 1,
        "total": 1
      },
      "stage": "s2",
      "state": "done",
      "track": 2,
      "updated_at": 1790906967.374741
    },
    {
      "attempts": 1,
      "error": null,
      "id": 4,
      "lane": "hub",
      "progress": null,
      "stage": "s3",
      "state": "done",
      "track": null,
      "updated_at": 1790906967.5350342
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790906967.36129,
    "session": 60,
    "stage3": {
      "at": 1790906967.534225,
      "branch": "scribe/session-060",
      "commit": "c1ea4712379394b67c74ed959c731a70349e87ec",
      "pushed": false,
      "utterances": 2
    },
    "tracks": [
      {
        "discord_id": "1001",
        "duration_s": 1.0,
        "file": "1-gm_user.wav",
        "index": 1,
        "speaker": {
          "label": "Gamemaster/DM",
          "pc": null,
          "role": "dm"
        },
        "username": "gm_user"
      },
      {
        "discord_id": "1002",
        "duration_s": 1.0,
        "file": "2-pat_user.wav",
        "index": 2,
        "speaker": {
          "label": "Pat/Alpha",
          "pc": "alpha",
          "role": "player"
        },
        "username": "pat_user"
      }
    ],
    "unmapped": []
  },
  "number": 60,
  "state": "ready"
}
"""#

    static let sessionBlocked = #"""
{
  "created_at": 1790906967.540237,
  "detail": "Add to campaign.yaml, then retry: stranger (999)",
  "jobs": [
    {
      "attempts": 1,
      "error": "unmapped speaker(s): stranger (999)",
      "id": 5,
      "lane": "hub",
      "progress": null,
      "stage": "s1",
      "state": "blocked",
      "track": null,
      "updated_at": 1790906967.566498
    }
  ],
  "manifest": {
    "craig": {
      "recording_id": "TESTREC",
      "start_time": "2026-10-01T00:00:00.000Z"
    },
    "created_at": 1790906967.566175,
    "session": 61,
    "stage3": null,
    "tracks": [
      {
        "discord_id": "999",
        "duration_s": 1.0,
        "file": "1-stranger.wav",
        "index": 1,
        "speaker": null,
        "username": "stranger"
      }
    ],
    "unmapped": [
      {
        "discord_id": "999",
        "index": 1,
        "username": "stranger"
      }
    ]
  },
  "number": 61,
  "state": "blocked"
}
"""#

    static let utterances = #"""
{
  "offset": 0,
  "total": 2,
  "utterances": [
    {
      "confidence": 0.9,
      "end_ms": 1800,
      "id": "t1-1000",
      "role": "dm",
      "speaker": "Gamemaster/DM",
      "start_ms": 1000,
      "text": "Line from track 1.",
      "track": 1
    },
    {
      "confidence": 0.9,
      "end_ms": 2800,
      "id": "t2-2000",
      "role": "player",
      "speaker": "Pat/Alpha",
      "start_ms": 2000,
      "text": "Line from track 2.",
      "track": 2
    }
  ]
}
"""#

    static let campaign = #"""
{
  "speakers": [
    {
      "discord_id": "1001",
      "label": "Gamemaster/DM",
      "role": "dm",
      "usernames": [
        "gm_user"
      ]
    },
    {
      "discord_id": "1002",
      "label": "Pat/Alpha",
      "pc": "alpha",
      "role": "player",
      "usernames": [
        "pat_user"
      ]
    }
  ],
  "vocabulary_prompt": "A game in a test world. Alpha talks with Beta."
}
"""#

    static let devices = #"""
{
  "devices": [
    {
      "created_at": 1790906967.3024378,
      "id": "7c1f9db3",
      "last_seen": 1790906967.575691,
      "name": "Fixture Mac",
      "revoked_at": null,
      "scope": "app"
    },
    {
      "created_at": 1790906967.303444,
      "id": "406c5b14",
      "last_seen": 1790906967.3755698,
      "name": "mac-worker",
      "revoked_at": null,
      "scope": "worker"
    }
  ]
}
"""#

    static let upload = #"""
{
  "job": 1,
  "session": 60
}
"""#

}
